# Generated by Django 3.0.8 on 2020-07-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='TypeOfChoice',
            field=models.CharField(choices=[('1', 'Ответ текстом'), ('2', 'ответ с выбором одного варианта'), ('3', 'ответ с выбором нескольких вариантов')], default='1', max_length=1),
        ),
    ]
