# Generated by Django 3.0.8 on 2020-07-06 09:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, help_text='Уникальный ID пользователя', primary_key=True, serialize=False)),
                ('poll', models.CharField(help_text='Название опроса', max_length=200)),
                ('description', models.CharField(help_text='Описание опроса', max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='Дата начала опроса')),
                ('finish_date', models.DateTimeField(blank=True, verbose_name='Дата окончания опроса')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Вопрос', max_length=200)),
                ('choice', models.CharField(help_text='Варианты ответа', max_length=200)),
                ('votes', models.CharField(help_text='Введите ответ', max_length=20, null=True)),
                ('TypeOfChoice', models.CharField(blank=True, choices=[('1', 'Ответ текстом'), ('2', 'ответ с выбором одного варианта'), ('3', 'ответ с выбором нескольких вариантов')], default='1', help_text='Выбор типа ответа', max_length=1)),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Poll')),
            ],
        ),
    ]
