# Generated by Django 3.0.8 on 2020-07-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.CharField(blank=True, default=1, help_text='Введите ответ', max_length=20),
            preserve_default=False,
        ),
    ]
