# Generated by Django 3.0.8 on 2020-07-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200706_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='TypeOfChoice',
            field=models.CharField(choices=[('1', 'Ответ текстом'), ('2', 'ответ с выбором одного варианта'), ('3', 'ответ с выбором нескольких вариантов')], default='1', help_text='Выбор типа ответа', max_length=1),
        ),
        migrations.AlterField(
            model_name='poll',
            name='finish_date',
            field=models.DateField(null=True, verbose_name='Дата окончания опроса'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала опроса'),
        ),
    ]
